Packer base
Otus-DevOps-2017-11/enotowombat_infra pull request #4
Opened 2017-12-22 18:52 UTC by enotowombat

Homework 7

2017-12-26 12:36 UTC, vitkhab requested changes
Хоть у меня и получилось запустить проект, но не с первой попытки.

Требуется добавить:
- Файл `variables.json.example`
- Исправить скрипты деплоя
- Поправить шаблоны `packer`
- Добавить документацию о доп заданиях

2017-12-26 12:36 UTC, vitkhab commented on packer/ubuntu16.json
> +      "script": "scripts/install_ruby.sh",
Конфигурация выдает ошибку 
```
* Bad script 'scripts/install_ruby.sh': stat scripts/install_ruby.sh: no such file or directory
```

2017-12-26 12:36 UTC, vitkhab commented on packer/immutable.json
> +      "script": "config-scripts/deploy.sh",
Судя по файлам в проекте, тут указан неправильный скрипт деплоя

2017-12-26 12:36 UTC, vitkhab commented on packer/files/deploy.sh
> +git clone https://github.com/Otus-DevOps-2017-11/reddit.git
Тут где-то спряталась ошибка

2017-12-26 14:29 UTC, enotowombat commented
Исправил. Но возможно что-то еще неправильно с размещением файлов, я запутался в несмерженных бранчах

2017-12-27 11:27 UTC, vitkhab requested changes
Хорошо поработал над ошибками.
Осталось последнее. Приведи, пожалуйста, в порядок `variables.json.example`.

2017-12-27 11:27 UTC, vitkhab commented on packer/variables.json.example
> +"variables":
Лишняя строчка

2017-12-27 11:27 UTC, vitkhab commented on packer/variables.json.example
> +    "image_name": "reddit-full-{{timestamp}}",
Использование переменных и функций внутри `variables`-файла невозможно.
Если оставить как есть, то получаю ошибку
```
==> googlecompute: Error waiting for image: googleapi: Error 400: Invalid value for field 'resource.name': 'reddit-full-{{timestamp}}'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

2017-12-27 12:52 UTC, enotowombat commented
Спасибо, исправил. packer validate -var-file=variables.json.example ubuntu16.json говорит ОК
Я файл-то добавил, но не использовал, все переменные определены в шаблоне.

2017-12-27 14:52 UTC, vitkhab approved these changes
Все круто! Молодец!

Менять `image_name` и `image_family` не обязательно.

2017-12-27 14:52 UTC, vitkhab commented on packer/ubuntu16.json
> +    "image_family": "{{user `image_family`}}",
Чтобы избежать рассхождения имен и семейств образов, я бы предложил бы написать так 
```
"image_name": "{{user `image_family`}}-{{timestamp}}",
"image_family": "{{user `image_family`}}",
```

2017-12-27 18:46 UTC, merged